import { useEffect, useRef, useState } from "react";
import { playSound } from "../../audio/soundEngine";
import "./RandomSeatingScreen.css";
const PHASE_DELAYS={ready:650,reaching:900,lifting:1150,seating:650};
function RandomSeatingScreen({entrants=[],players=[],onComplete}){const[seatIndex,setSeatIndex]=useState(0);const[phase,setPhase]=useState("ready");const lastCue=useRef("");const ceremonyComplete=seatIndex>=players.length;const drawnPlayer=ceremonyComplete?null:players[seatIndex];const seatedNames=new Set(players.slice(0,seatIndex).map(player=>player.name));
useEffect(()=>{const cue=`${seatIndex}-${phase}`;if(lastCue.current===cue)return;lastCue.current=cue;if(phase==="reaching")playSound("draw");if(phase==="lifting")playSound("gold");if(phase==="seating")playSound("seat");},[phase,seatIndex]);
useEffect(()=>{if(ceremonyComplete)return undefined;const timer=setTimeout(()=>{if(phase==="ready")setPhase("reaching");else if(phase==="reaching")setPhase("lifting");else if(phase==="lifting")setPhase("seating");else{setSeatIndex(index=>index+1);setPhase("ready");}},PHASE_DELAYS[phase]);return()=>clearTimeout(timer);},[ceremonyComplete,phase]);
return <section className="seating-ceremony-screen"><header className="seating-ceremony-heading"><p>Royal Seating Ceremony</p><h1>Drawing the Royal Court</h1><span>Chance alone will decide who begins the match.</span></header><div className="seating-ceremony-stage"><div className="seating-name-pool" aria-label="Names placed into the royal hat"><h2>Names in the Hat</h2>{entrants.map((entrant,index)=><span key={`${entrant.name}-${index}`} className={seatedNames.has(entrant.name)?"drawn":"waiting"}>{entrant.name}</span>)}</div><div className={`royal-draw-scene phase-${phase}`} aria-live="polite"><div className="royal-hat" aria-hidden="true">🎩</div><div className="royal-hand" aria-hidden="true">🫱</div><div className="royal-name-slip">{phase==="lifting"||phase==="seating"?drawnPlayer?.name:"?"}</div><div className="royal-sparkles" aria-hidden="true">✦ ✧ ✦</div><p className="royal-draw-caption">{ceremonyComplete?"The Royal Court is seated.":phase==="ready"?`Preparing the draw for Seat ${seatIndex+1}`:phase==="reaching"?"Reaching into the royal hat...":phase==="lifting"?`${drawnPlayer?.name} has been drawn!`:`${drawnPlayer?.name} takes Seat ${seatIndex+1}`}</p></div><div className="seating-results" aria-label="Randomized seating results"><h2>Royal Seating</h2>{players.map((player,index)=>{const isRevealed=index<seatIndex;const isArriving=index===seatIndex&&phase==="seating";return <article key={player.id||`${player.name}-${index}`} className={`seating-result-card ${isRevealed||isArriving?"revealed":"hidden"} ${isArriving?"arriving":""}`}><span>Seat {index+1}</span><strong>{isRevealed||isArriving?player.name:"Awaiting Draw"}</strong><small>{index===0&&(isRevealed||isArriving)?"First Turn":isRevealed||isArriving?"Royal Contender":"Not Yet Drawn"}</small></article>;})}</div></div><button type="button" className="seating-begin-button" disabled={!ceremonyComplete} onClick={onComplete}>{ceremonyComplete?"Begin the Match":"Drawing Seats..."}</button></section>}
export default RandomSeatingScreen;
