export const DATABASE_SCHEMA_VERSION = 6;
export const schemaStatements = [
`CREATE TABLE IF NOT EXISTS schema_versions (version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
`CREATE TABLE IF NOT EXISTS users (user_id TEXT PRIMARY KEY, username TEXT NOT NULL COLLATE NOCASE UNIQUE, password_hash TEXT NOT NULL, first_name TEXT NOT NULL, last_name TEXT NOT NULL, is_admin INTEGER NOT NULL DEFAULT 0 CHECK (is_admin IN (0,1)), is_active INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, last_login_at TEXT)`,
`CREATE TABLE IF NOT EXISTS player_statistics (user_id TEXT PRIMARY KEY, games_played INTEGER NOT NULL DEFAULT 0, games_won INTEGER NOT NULL DEFAULT 0, games_lost INTEGER NOT NULL DEFAULT 0, first_place_finishes INTEGER NOT NULL DEFAULT 0, second_place_finishes INTEGER NOT NULL DEFAULT 0, third_place_finishes INTEGER NOT NULL DEFAULT 0, fourth_place_finishes INTEGER NOT NULL DEFAULT 0, cards_purchased INTEGER NOT NULL DEFAULT 0, nobles_acquired INTEGER NOT NULL DEFAULT 0, reserved_cards_purchased INTEGER NOT NULL DEFAULT 0, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE)`,
`CREATE TABLE IF NOT EXISTS rooms (room_id TEXT PRIMARY KEY, room_code TEXT UNIQUE, room_name TEXT NOT NULL, host_user_id TEXT NOT NULL, visibility TEXT NOT NULL CHECK (visibility IN ('public','private')), password_hash TEXT, maximum_players INTEGER NOT NULL CHECK (maximum_players BETWEEN 2 AND 4), spectators_allowed INTEGER NOT NULL DEFAULT 1 CHECK (spectators_allowed IN (0,1)), victory_target INTEGER NOT NULL DEFAULT 20, status TEXT NOT NULL DEFAULT 'waiting' CHECK (status IN ('waiting','in_progress','finished','closed')), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (host_user_id) REFERENCES users(user_id))`,
`CREATE TABLE IF NOT EXISTS room_members (room_member_id TEXT PRIMARY KEY, room_id TEXT NOT NULL, user_id TEXT, member_type TEXT NOT NULL CHECK (member_type IN ('human','ai','spectator')), role TEXT NOT NULL CHECK (role IN ('host','player','spectator')), seat_number INTEGER CHECK (seat_number BETWEEN 1 AND 4), ai_personality_id TEXT, connection_id TEXT, is_connected INTEGER NOT NULL DEFAULT 0 CHECK (is_connected IN (0,1)), is_ready INTEGER NOT NULL DEFAULT 0 CHECK (is_ready IN (0,1)), joined_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (room_id) REFERENCES rooms(room_id) ON DELETE CASCADE, FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE, UNIQUE (room_id,seat_number))`,
`CREATE TABLE IF NOT EXISTS matches (match_id TEXT PRIMARY KEY, room_id TEXT, status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','completed','abandoned')), current_turn INTEGER NOT NULL DEFAULT 0, game_state_json TEXT NOT NULL, state_version INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, completed_at TEXT, FOREIGN KEY (room_id) REFERENCES rooms(room_id) ON DELETE SET NULL)`,
`CREATE TABLE IF NOT EXISTS match_players (match_player_id TEXT PRIMARY KEY, match_id TEXT NOT NULL, user_id TEXT, player_type TEXT NOT NULL CHECK (player_type IN ('human','ai')), display_name TEXT NOT NULL, seat_number INTEGER NOT NULL CHECK (seat_number BETWEEN 1 AND 4), ai_personality_id TEXT, final_placement INTEGER CHECK (final_placement BETWEEN 1 AND 4), points INTEGER NOT NULL DEFAULT 0, cards_purchased INTEGER NOT NULL DEFAULT 0, nobles_claimed INTEGER NOT NULL DEFAULT 0, FOREIGN KEY (match_id) REFERENCES matches(match_id) ON DELETE CASCADE, FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE SET NULL, UNIQUE (match_id,seat_number))`,
`CREATE INDEX IF NOT EXISTS idx_rooms_status_visibility ON rooms(status,visibility)`,
`CREATE INDEX IF NOT EXISTS idx_room_members_room_id ON room_members(room_id)`,
`CREATE INDEX IF NOT EXISTS idx_matches_status ON matches(status)`,
`CREATE INDEX IF NOT EXISTS idx_matches_local_recovery ON matches(room_id,status,updated_at)`,
`CREATE TABLE IF NOT EXISTS community_posts (post_id TEXT PRIMARY KEY, user_id TEXT NOT NULL, category TEXT NOT NULL CHECK (category IN ('general','bug','suggestion','balance','question','praise')), title TEXT NOT NULL, body TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','under_review','planned','implemented','closed')), developer_response TEXT, is_pinned INTEGER NOT NULL DEFAULT 0 CHECK (is_pinned IN (0,1)), is_locked INTEGER NOT NULL DEFAULT 0 CHECK (is_locked IN (0,1)), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE)`,
`CREATE TABLE IF NOT EXISTS community_replies (reply_id TEXT PRIMARY KEY, post_id TEXT NOT NULL, user_id TEXT NOT NULL, body TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (post_id) REFERENCES community_posts(post_id) ON DELETE CASCADE, FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE)`,
`CREATE TABLE IF NOT EXISTS community_votes (post_id TEXT NOT NULL, user_id TEXT NOT NULL, vote INTEGER NOT NULL CHECK (vote IN (-1,1)), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (post_id,user_id), FOREIGN KEY (post_id) REFERENCES community_posts(post_id) ON DELETE CASCADE, FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE)`,
`CREATE INDEX IF NOT EXISTS idx_community_posts_created_at ON community_posts(created_at DESC)`,
`CREATE INDEX IF NOT EXISTS idx_community_posts_category_status ON community_posts(category,status)`,
`CREATE INDEX IF NOT EXISTS idx_community_replies_post_id ON community_replies(post_id,created_at)`,
`CREATE INDEX IF NOT EXISTS idx_community_votes_post_id ON community_votes(post_id)`
];
