import crypto from "node:crypto";
import { getDatabase } from "../database/database.js";
const CATEGORIES=new Set(["general","bug","suggestion","balance","question","praise"]);
const STATUSES=new Set(["open","under_review","planned","implemented","closed"]);
const clean=(value,max)=>String(value||"").trim().slice(0,max);
const displayNameSql=`CASE WHEN TRIM(u.last_name)='' THEN u.first_name ELSE u.first_name||' '||UPPER(SUBSTR(u.last_name,1,1))||'.' END`;
function adminUser(user){
  if (!user?.userId) return false;
  return Boolean(getDatabase().prepare("SELECT is_admin FROM users WHERE user_id = ?").get(user.userId)?.is_admin);
}
function mapPost(row,replies=[]){return{postId:row.post_id,userId:row.user_id,authorName:row.author_name,category:row.category,title:row.title,body:row.body,status:row.status,developerResponse:row.developer_response,isPinned:Boolean(row.is_pinned),isLocked:Boolean(row.is_locked),createdAt:row.created_at,updatedAt:row.updated_at,score:Number(row.score)||0,replyCount:Number(row.reply_count)||0,myVote:Number(row.my_vote)||0,replies};}
export function listCommunityPosts(userId,filters={}){const db=getDatabase(),where=[],params=[];if(CATEGORIES.has(filters.category)){where.push('p.category=?');params.push(filters.category);}if(filters.status&&filters.status!=='all'){where.push('p.status=?');params.push(filters.status);}const q=clean(filters.search,100);if(q){where.push('(p.title LIKE ? OR p.body LIKE ?)');params.push(`%${q}%`,`%${q}%`);}const secondary=filters.sort==='top'?'score DESC,p.created_at DESC':filters.sort==='oldest'?'p.created_at ASC':'p.created_at DESC';const rows=db.prepare(`SELECT p.*,${displayNameSql} author_name,COALESCE((SELECT SUM(v.vote) FROM community_votes v WHERE v.post_id=p.post_id),0) score,(SELECT COUNT(*) FROM community_replies r WHERE r.post_id=p.post_id) reply_count,COALESCE((SELECT v.vote FROM community_votes v WHERE v.post_id=p.post_id AND v.user_id=?),0) my_vote FROM community_posts p JOIN users u ON u.user_id=p.user_id ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY p.is_pinned DESC,${secondary} LIMIT 200`).all(userId,...params);return rows.map(mapPost);}
export function getCommunityPost(postId,userId){const db=getDatabase();const row=db.prepare(`SELECT p.*,${displayNameSql} author_name,COALESCE((SELECT SUM(v.vote) FROM community_votes v WHERE v.post_id=p.post_id),0) score,(SELECT COUNT(*) FROM community_replies r WHERE r.post_id=p.post_id) reply_count,COALESCE((SELECT v.vote FROM community_votes v WHERE v.post_id=p.post_id AND v.user_id=?),0) my_vote FROM community_posts p JOIN users u ON u.user_id=p.user_id WHERE p.post_id=?`).get(userId,postId);if(!row)return null;const replies=db.prepare(`SELECT r.reply_id replyId,r.post_id postId,r.user_id userId,${displayNameSql} authorName,r.body,r.created_at createdAt,r.updated_at updatedAt FROM community_replies r JOIN users u ON u.user_id=r.user_id WHERE r.post_id=? ORDER BY r.created_at`).all(postId);return mapPost(row,replies);}
export function createCommunityPost(userId,input={}){const category=CATEGORIES.has(input.category)?input.category:'general',title=clean(input.title,120),body=clean(input.body,4000);if(!title||!body)return{ok:false,status:400,message:'Title and message are required.'};const id=crypto.randomUUID();getDatabase().prepare('INSERT INTO community_posts(post_id,user_id,category,title,body) VALUES(?,?,?,?,?)').run(id,userId,category,title,body);return{ok:true,status:201,post:getCommunityPost(id,userId)};}
export function addCommunityReply(postId,userId,input={}){const body=clean(input.body,2000),db=getDatabase(),post=db.prepare('SELECT is_locked FROM community_posts WHERE post_id=?').get(postId);if(!body)return{ok:false,status:400,message:'Reply text is required.'};if(!post)return{ok:false,status:404,message:'That discussion was not found.'};if(post.is_locked)return{ok:false,status:409,message:'This discussion is locked.'};db.prepare('INSERT INTO community_replies(reply_id,post_id,user_id,body) VALUES(?,?,?,?)').run(crypto.randomUUID(),postId,userId,body);return{ok:true,status:201,post:getCommunityPost(postId,userId)};}
export function voteCommunityPost(postId,userId,value){const vote=Number(value),db=getDatabase();if(![-1,0,1].includes(vote))return{ok:false,status:400,message:'Choose a valid vote.'};if(!db.prepare('SELECT 1 FROM community_posts WHERE post_id=?').get(postId))return{ok:false,status:404,message:'That discussion was not found.'};if(vote===0)db.prepare('DELETE FROM community_votes WHERE post_id=? AND user_id=?').run(postId,userId);else db.prepare(`INSERT INTO community_votes(post_id,user_id,vote) VALUES(?,?,?) ON CONFLICT(post_id,user_id) DO UPDATE SET vote=excluded.vote,updated_at=CURRENT_TIMESTAMP`).run(postId,userId,vote);return{ok:true,status:200,post:getCommunityPost(postId,userId)};}
export function moderateCommunityPost(postId,user,input={}){if(!adminUser(user))return{ok:false,status:403,message:'Administrator access is required.'};const db=getDatabase(),post=db.prepare('SELECT * FROM community_posts WHERE post_id=?').get(postId);if(!post)return{ok:false,status:404,message:'That discussion was not found.'};const status=STATUSES.has(input.status)?input.status:post.status,title=input.title===undefined?post.title:clean(input.title,120),body=input.body===undefined?post.body:clean(input.body,4000),response=input.developerResponse===undefined?post.developer_response:clean(input.developerResponse,4000),pinned=input.isPinned===undefined?post.is_pinned:Number(Boolean(input.isPinned)),locked=input.isLocked===undefined?post.is_locked:Number(Boolean(input.isLocked));if(!title||!body)return{ok:false,status:400,message:'Title and message are required.'};db.prepare(`UPDATE community_posts SET status=?,title=?,body=?,developer_response=?,is_pinned=?,is_locked=?,updated_at=CURRENT_TIMESTAMP WHERE post_id=?`).run(status,title,body,response||null,pinned,locked,postId);return{ok:true,status:200,post:getCommunityPost(postId,user.userId)};}
export function deleteCommunityPost(postId,user){if(!adminUser(user))return{ok:false,status:403,message:'Administrator access is required.'};const result=getDatabase().prepare('DELETE FROM community_posts WHERE post_id=?').run(postId);return result.changes?{ok:true,status:200,deleted:true}:{ok:false,status:404,message:'That discussion was not found.'};}
export function deleteCommunityReply(postId,replyId,user){if(!adminUser(user))return{ok:false,status:403,message:'Administrator access is required.'};const result=getDatabase().prepare('DELETE FROM community_replies WHERE reply_id=? AND post_id=?').run(replyId,postId);return result.changes?{ok:true,status:200,post:getCommunityPost(postId,user.userId)}:{ok:false,status:404,message:'That reply was not found.'};}
export function isCommunityAdmin(user){return adminUser(user);}
